remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: Improving Word-level Timestamps for OpenASR
description: Documenting the process of improving timestamp quality for select transcription models with OpenASR
